version: '3'
services:
  db:
    build: ./db
    container_name: db
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=baltimoreCrimeData
      - MYSQL_USER=APIUser
      - MYSQL_PASSWORD=DjangoRestAPIUser1!
    ports:
      - "3306:3306"
  
  rest:
    build: ./rest
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    restart: on-failure

